# Convenience class that defines a static list of +States+ that are displayed in a drop-down list for an +Interest Point+
class States
	
	# A constant hash that contains all state abbreviations and their names. Taken from http://www.dzone.com/snippets/us-state-abbreviations-full
  	LIST = {
	  'AL' => 'Alabama',
	  'AK' => 'Alaska',
	  'AS' => 'America Samoa',
	  'AZ' => 'Arizona',
	  'AR' => 'Arkansas',
	  'CA' => 'California',
	  'CO' => 'Colorado',
	  'CT' => 'Connecticut',
	  'DE' => 'Delaware',
	  'DC' => 'District of Columbia',
	  'FL' => 'Florida',
	  'GA' => 'Georgia',
	  'GU' => 'Guam',
	  'HI' => 'Hawaii',
	  'ID' => 'Idaho',
	  'IL' => 'Illinois',
	  'IN' => 'Indiana',
	  'IA' => 'Iowa',
	  'KS' => 'Kansas',
	  'KY' => 'Kentucky',
	  'LA' => 'Louisiana',
	  'ME' => 'Maine',
	  'MD' => 'Maryland',
	  'MA' => 'Massachusetts',
	  'MI' => 'Michigan',
	  'MN' => 'Minnesota',
	  'MS' => 'Mississippi',
	  'MO' => 'Missouri',
	  'MT' => 'Montana',
	  'NE' => 'Nebraska',
	  'NV' => 'Nevada',
	  'NH' => 'New Hampshire',
	  'NJ' => 'New Jersey',
	  'NM' => 'New Mexico',
	  'NY' => 'New York',
	  'NC' => 'North Carolina',
	  'ND' => 'North Dakota',
	  'OH' => 'Ohio',
	  'OK' => 'Oklahoma',
	  'OR' => 'Oregon',
	  'PA' => 'Pennsylvania',
	  'RI' => 'Rhode Island',
	  'SC' => 'South Carolina',
	  'SD' => 'South Dakota',
	  'TN' => 'Tennessee',
	  'TX' => 'Texas',
	  'UT' => 'Utah',
	  'VT' => 'Vermont',
	  'VA' => 'Virginia',
	  'WA' => 'Washington',
	  'WV' => 'West Virginia',
	  'WI' => 'Wisconsin',
	  'WY' => 'Wyoming'
	}

end